name: domain
description: domain layer use-cases definition those will intact with UI.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  data:
    path: ../data